name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Miguerfi/Miguerfi@main
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_7f8aeaec-09d0-47d4-8bba-b44fb9605f62 }}
          GH_TOKEN: ${{ secrets.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 }}
          SHOW_OS: "True"
          COMMIT_BY_ME: "True"
          SHOW_LANGUAGE: "True"
