name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: <Miguerfi/Miguerfi>
          SHOW_OS: "True"
      - uses: lowlighter/metrics@latest
        with:
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: http://wakapi.dev                    # Wakatime url endpoint
          plugin_wakatime_user: .user.login    
